name: Build-Semaphore-Agent-Docker

run-name: build-semaphore-agent-docker-${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:
  
jobs:
  build-default-semaphore-agent-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate-github-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.CLEVERTAP_SNE_BOT_ID }}
          private_key: ${{ secrets.CLEVERTAP_SNE_BOT_PRIVATE_ACCESS_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-github-token.outputs.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./semaphore-agent-docker
          push: true
          tags: yashprime07/semaphore-agent:latest
          platforms: linux/amd64,linux/arm64