name: Build-Semaphore-Agent-Docker

run-name: build-semaphore-agent-docker-${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:
  
jobs:
  build-default-semaphore-agent-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: artifactory.clevertap.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./semaphore-agent-docker
          push: true
          tags: artifactory.clevertap.net/semaphore-agent:${{ github.ref_name }}-${{ github.run_number }}
          platforms: linux/amd64