name: Copy-S3-Packages-To-Semaphore-Agent

run-name: copy-s3-packages-${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      Region:
        description: "AWS Region"
        required: false
        default: "eu-west-1"

jobs:
  copy-s3-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.Region }}

      - name: Create local directories
        run: |
          mkdir -p ./local-packages/node-v18-18-1
          mkdir -p ./local-packages/node-v18-18-2
          mkdir -p ./local-packages/node-v14-18-2
          mkdir -p ./local-packages/jq

      - name: Copy packages from source S3 to local
        run: |
          echo "Copying node-v18-18-1..."
          aws s3 cp s3://bamboo-packages/node-v18-18-1/ ./local-packages/node-v18-18-1/ --recursive
          
          echo "Copying node-v18-18-2..."
          aws s3 cp s3://bamboo-packages/node-v18-18-2/ ./local-packages/node-v18-18-2/ --recursive
          
          echo "Copying node-v14-18-2..."
          aws s3 cp s3://bamboo-packages/node-v14-18-2/ ./local-packages/node-v14-18-2/ --recursive
          
          echo "Copying jq..."
          aws s3 cp s3://bamboo-packages/jq/ ./local-packages/jq/ --recursive

      - name: Verify local files
        run: |
          echo "Verifying downloaded files..."
          find ./local-packages -type f -exec ls -la {} \;
          echo "Total files downloaded: $(find ./local-packages -type f | wc -l)"

      - name: Copy packages from local to destination S3
        run: |
          echo "Uploading packages to destination S3..."
          aws s3 cp ./local-packages/ s3://system-sharedresources-ssms3bucket-fp7gg9zzae0f/semaphore-agent/ --recursive

      - name: Verify destination S3 upload
        run: |
          echo "Verifying files in destination S3..."
          aws s3 ls s3://system-sharedresources-ssms3bucket-fp7gg9zzae0f/semaphore-agent/ --recursive

      - name: Cleanup local files
        run: |
          echo "Cleaning up local files..."
          rm -rf ./local-packages
          echo "Cleanup completed"