name: Build-Ultron-Semaphore-Agent-Ami

run-name: build-ultron-semaphore-agent-ami-${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:

jobs:
  build-ultron-semaphore-agent-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build-Cloudformation repo
        uses: actions/checkout@v4
        with:
          show-progress: 'false'

      - name: Setup packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          version: 1.2.5

      - name: Validate packer
        run: |
          set -exou pipefail
          packer validate semaphore-agent-ami/ultron/packer-ultron-semaphore-agent.json
        env:
          BUILD_INSTANCE_TYPE: t2.micro
          BUILD_SOURCE_IMAGE_NAME: ultron-semaphore-agent-15875630838-v0.4.0-ubuntu-focal-x86_64-c6a7b62f0ac8886b16898d407678b356-1750853420
          AWS_MAX_ATTEMPTS: 300
          AWS_POLL_DELAY_SECONDS: 30
          AWS_REGION: eu-west-1

      - name: Build packer
        run: |
          set -exou pipefail
          packer build semaphore-agent-ami/ultron/packer-ultron-semaphore-agent.json
        env:
          BUILD_INSTANCE_TYPE: t2.micro
          BUILD_SOURCE_IMAGE_NAME: ultron-semaphore-agent-15875630838-v0.4.0-ubuntu-focal-x86_64-c6a7b62f0ac8886b16898d407678b356-1750853420
          AWS_MAX_ATTEMPTS: 300
          AWS_POLL_DELAY_SECONDS: 30
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
